# syntax=docker/dockerfile:1

ARG KIND=plugins
ARG USERNAME=codeclarity
ARG PLUGINNAME=plugin

# DEV IMAGE
FROM golang:1.27.1-alpine@sha256:8a5910f31396cd4d89662f56c68b3ae31d374308270a1c3bd96672ee5ed43414 AS plugin-dev
ARG KIND
ARG PLUGINNAME
WORKDIR /codeclarity/${KIND}/${PLUGINNAME}
ADD .cloud/docker/config/* /root
RUN apk add git
RUN go install github.com/air-verse/air@v1.64.5
CMD ["air", "-c", ".air.toml"]

# DEBUG IMAGE
FROM golang:1.27.1-alpine@sha256:8a5910f31396cd4d89662f56c68b3ae31d374308270a1c3bd96672ee5ed43414 AS plugin-debug
ARG KIND
ARG PLUGINNAME
ENV KIND=${KIND}
ENV PLUGINNAME=${PLUGINNAME}
RUN apk add git
RUN go install github.com/go-delve/delve/cmd/dlv@latest
ADD .cloud/docker/config/* /root
WORKDIR /codeclarity/${KIND}/${PLUGINNAME}
CMD ["/go/bin/dlv", "debug", ".", "--headless", "--listen=:40000", "--accept-multiclient"]
# CMD tail -f /dev/null


# BUILD IMAGE
FROM golang:1.27.1-alpine@sha256:8a5910f31396cd4d89662f56c68b3ae31d374308270a1c3bd96672ee5ed43414 AS plugin-build
ARG KIND
ARG PLUGINNAME
ARG DIRNAME=
COPY . /codeclarity_src
RUN DIR="${DIRNAME:-${PLUGINNAME}}" && \
    if [ -d "/codeclarity_src/${KIND}/$DIR" ]; then \
      mv /codeclarity_src /codeclarity; \
      if [ "$DIR" != "${PLUGINNAME}" ]; then \
        ln -s "$DIR" "/codeclarity/${KIND}/${PLUGINNAME}"; \
      fi; \
    else \
      mkdir -p /codeclarity/${KIND} && \
      mv /codeclarity_src /codeclarity/${KIND}/${PLUGINNAME} && \
      rm -f /codeclarity/${KIND}/${PLUGINNAME}/go.work; \
    fi
WORKDIR /codeclarity/${KIND}/${PLUGINNAME}
RUN apk update && apk upgrade --no-cache
RUN apk add git
RUN [ "go", "build", "-o", "plugin" ]

# PRODUCTION IMAGE
FROM alpine:3.24.2@sha256:294b683cb724975bec92580e1e685676bd4b50bda910ddb8c51d4cabeaec77e6 AS plugin
ARG KIND
ARG USERNAME
ARG PLUGINNAME
RUN apk update && apk upgrade --no-cache
RUN apk add --no-cache git
RUN addgroup -S ${USERNAME} --gid 1001 && adduser -S ${USERNAME} -G ${USERNAME} --uid 1001 -D
RUN mkdir /private
RUN chown -R ${USERNAME}:${USERNAME} /private
USER ${USERNAME}
WORKDIR /home/${USERNAME}/${PLUGINNAME}
COPY --from=plugin-build --chown=codeclarity:codeclarity /codeclarity/${KIND}/${PLUGINNAME}/plugin .
COPY --from=plugin-build --chown=codeclarity:codeclarity /codeclarity/${KIND}/${PLUGINNAME}/config.json .

ENTRYPOINT [ "./plugin" ]
